# Makefile for swupdate
#
# Copyright (C) 2013 Stefano Babic <stefano.babic@swupdate.org>
#
# Based on busybox build system:
#
# Copyright (C) 1999-2005 by Erik Andersen <andersen@codepoet.org>
#
# SPDX-License-Identifier:     GPL-2.0-only

obj-y += swupdate.o \
	 cpio_utils.o \
	 notifier.o \
	 handler.o \
	 bootloader.o \
	 hw-compatibility.o \
	 install_from_file.o \
	 util.o \
	 parser.o \
	 pctl.o \
	 state.o \
	 syslog.o \
	 installer.o \
	 network_utils.o \
	 network_thread.o \
	 stream_interface.o \
	 progress_thread.o \
	 parsing_library.o \
	 artifacts_versions.o \
	 swupdate_dict.o \
	 swupdate_vars.o \
	 semver.o \
	 strlcpy.o
