# SPDX-FileCopyrightText: 2021 Weidmueller Interface GmbH & Co. KG
#
# SPDX-License-Identifier: GPL-2.0-only

lib-$(CONFIG_FAT_FILESYSTEM) += diskio.o \
				fat_fs.o \
				ff.o
lib-$(CONFIG_EXT_FILESYSTEM) += mke2fs.o \
