Document: swupdate
Title: Debian swupdate Manual
Author: <insert document author here>
Abstract: This manual describes what swupdate is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/swupdate/swupdate.sgml.gz

Format: postscript
Files: /usr/share/doc/swupdate/swupdate.ps.gz

Format: text
Files: /usr/share/doc/swupdate/swupdate.text.gz

Format: HTML
Index: /usr/share/doc/swupdate/html/index.html
Files: /usr/share/doc/swupdate/html/*.html
