# Copyright (C) 2014-2018 Stefano Babic <stefano.babic@swupdate.org>
#
# SPDX-License-Identifier:     GPL-2.0-only
obj-$(CONFIG_LUA)	+= auxiliar.o lua_swupdate.o lua_compat_shared.o

EXTRA_CFLAGS += -fPIC
