# Copyright (C) 2014-2018 Stefano Babic <sbabic@denx.de>
#
# SPDX-License-Identifier:     GPL-2.0-only
#
obj-$(CONFIG_UBOOT)		+= uboot.o
obj-$(CONFIG_BOOTLOADER_NONE)	+= none.o
obj-$(CONFIG_BOOTLOADER_GRUB)	+= grub.o
obj-$(CONFIG_BOOTLOADER_EBG)	+= ebg.o
