# Copyright (C) 2014-2018 Stefano Babic <sbabic@denx.de>
#
# SPDX-License-Identifier:     GPL-2.0-only
#
lib-$(CONFIG_UBOOT)		+= uboot.o
lib-$(CONFIG_BOOTLOADER_NONE)	+= none.o
lib-$(CONFIG_BOOTLOADER_GRUB)	+= grub.o
lib-$(CONFIG_BOOTLOADER_EBG)		+= ebg.o
