lib-y				+= installer.o \
				   network_thread.o \
				   stream_interface.o \
				   progress_thread.o
lib-$(CONFIG_DOWNLOAD)		+= downloader.o
lib-$(CONFIG_MTD)		+= mtd-interface.o
lib-$(CONFIG_LUA)		+= lua_interface.o
lib-$(CONFIG_SIGNED_IMAGES)	+= verify_signature.o
